/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#341100",
        "surface-tint": "#565e74",
        "surface-container": "#e5eeff",
        "surface-variant": "#d3e4fe",
        "on-tertiary-container": "#008ebf",
        "primary-container": "#131b2e",
        "on-tertiary-fixed-variant": "#004c69",
        "secondary-fixed": "#ffdbca",
        "primary-fixed": "#dae2fd",
        "on-tertiary-fixed": "#001e2c",
        "surface-dim": "#cbdbf5",
        "tertiary": "#000000",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "surface-container-high": "#dce9ff",
        "outline": "#76777d",
        "on-secondary-container": "#5c2400",
        "on-secondary-fixed-variant": "#783200",
        "on-error": "#ffffff",
        "inverse-on-surface": "#eaf1ff",
        "on-primary-fixed-variant": "#3f465c",
        "primary-fixed-dim": "#bec6e0",
        "surface-container-low": "#eff4ff",
        "on-background": "#0b1c30",
        "outline-variant": "#c6c6cd",
        "on-surface-variant": "#45464d",
        "tertiary-fixed-dim": "#7bd0ff",
        "secondary-container": "#fd761a",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#ffb690",
        "surface-container-lowest": "#ffffff",
        "primary": "#000000",
        "surface-bright": "#f8f9ff",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#001e2c",
        "on-primary-container": "#7c839b",
        "on-surface": "#0b1c30",
        "on-primary-fixed": "#131b2e",
        "surface-container-highest": "#d3e4fe",
        "inverse-surface": "#213145",
        "background": "#f8f9ff",
        "secondary": "#9d4300",
        "error-container": "#ffdad6",
        "surface": "#f8f9ff",
        "inverse-primary": "#bec6e0",
        "tertiary-fixed": "#c4e7ff"
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "sm": "0.25rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "32px",
        "base": "4px",
        "gutter": "24px",
        "md": "24px",
        "margin-mobile": "16px",
        "xl": "64px",
        "lg": "40px",
        "sm": "16px",
        "xs": "8px"
      },
      fontFamily: {
        "body-lg": ["Lexend", "sans-serif"],
        "display-lg-mobile": ["Montserrat", "sans-serif"],
        "body-md": ["Lexend", "sans-serif"],
        "headline-sm": ["Montserrat", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "display-lg": ["Montserrat", "sans-serif"],
        "body-sm": ["Lexend", "sans-serif"],
        "label-bold": ["Lexend", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "display-lg-mobile": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "label-bold": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
